sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.3
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external --assume-extension
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true