sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6
script:
  - bundle exec rake test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
