sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.3
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external --assume-extension --file_ignore "/assets/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true