markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  # do not replace newlines by <br>s
  hard_wrap: false

timezone: America/Chicago

url: https://brianm.me
baseurl: ''

permalink: /posts/:slug
paginate: 5
paginate_path: /blog/page/:num/

exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - CNAME
  - LICENSE

sass:
  sass_dir: assets/css/_sass
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sass-converter
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate
  - rouge

exclude: [vendor]

# navigation
navigation:
  - text: About
    title: Extended Résumé
    url: /about
  - text: Blog
    title: Blog Posts
    url: /blog
  - text: Projects
    title: Projects
    url: /projects

# analytics
analytics:
  google:
    tracking_id: UA-44772557-2

# comments
comments:
  disqus:
    shortname: brianmme

# seo
title: Brian Mitchell
description: Blog posts, projects, social media presence, and more!
url: https://brianm.me

twitter:
  username: BrianMitchL

facebook:
  app_id:
  publisher:
  admins:

logo: /assets/images/BM-Logo.png

social:
  name: Brian Mitchell
  links:
    - https://github.com/BrianMitchL
    - https://facebook.com/BrianMitchL
    - https://twitter.com/BrianMitchL
    - https://plus.google.com/+BrianMitchell16/
    - https://www.instagram.com/bman4789
    - http://www.last.fm/user/bman4789
    - https://www.linkedin.com/in/brianscottmitchell
    - https://www.reddit.com/user/bman4789
    - https://open.spotify.com/user/1237277662
    - https://soundcloud.com/bman4789
    - https://steamcommunity.com/id/MagicBriBri
    - http://bman4789.tumblr.com
    - https://vine.co/bman4789
    - https://www.youtube.com/user/bman112234
    - https://www.snapchat.com/add/bman4789

google_site_verification: 4-mwXA7aYqZalRm3UuWpPv-aMyFT_zUtA_ks_RK7r5I
