title : Brian Mitchell

author :
  name : Brian Mitchell
  email : bman4789@gmail.com
  github : bman4789
  twitter : tech4789

url: http://bman4789.github.io
markdown: kramdown

exclude: ['README.md', '.gitignore', 'Gemfile', 'resource_creation']