markdown: kramdown

title : Brian Mitchell

author :
  name : Brian Mitchell
  email : bman4789@gmail.com
  github : bman4789
  twitter : tech4789

url: http://bman4789.github.io

navigation:
#      - text: Home
#        title: Back to home page
#        url: /
      - text: About Me
        title: A brief overview of me
        url: /about/
      - text: Posts
        title: Blog Posts
        url: /posts/

exclude: ['README.md', '.gitignore', 'Gemfile', 'resource_creation']