markdown: kramdown

title : Brian Mitchell
description: Old website with blog posts, links to other sites, an online resume, and more!

author :
  name : Brian Mitchell
  email : bman4789@gmail.com
  github : bman4789
  twitter : bman4789

url: http://github.brianm.me

navigation:
#      - text: Home
#        title: Back to home page
#        url: /
      - text: About Me
        title: A brief overview of me
        url: /about
      - text: Posts
        title: Blog Posts
        url: /posts
      - text: Angular
        title: Angular Demos
        url: https://brianm.me/
      - text: Other Sites
        title: Links to my other sites
        url: /other-sites

exclude: ['README.md', '.gitignore', 'Gemfile', 'resource_creation']

#enforce_ssl: github.brianm.me