markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  # do not replace newlines by <br>s
  hard_wrap: false
  toc_levels: 1..3

url: https://brianm.me
baseurl: ''

permalink: /posts/:title
paginate: 5
paginate_path: /blog/page/:num/

collections:
  living-docs:
    output: true

exclude:
  - .idea
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - CNAME
  - LICENSE
  - vendor

sass:
  sass_dir: assets/css/_sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sass-converter
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate
  - rouge

# navigation
navigation:
  - text: About
    title: Extended Résumé
    url: /about
  - text: Blog
    title: Blog Posts
    url: /blog
  - text: Living Docs
    title: Living Documents
    url: /living-docs
  - text: Projects
    title: Projects
    url: /projects
  - text: Slides
    title: Slides
    url: /slides

# analytics
analytics:
  google:
    tracking_id: UA-44772557-2

# comments
comments:
  disqus:
    shortname: brianmme

# seo
title: Brian Mitchell
description: Blog, projects, & online presence

twitter:
  username: BrianMitchL

facebook:
  app_id:
  publisher:
  admins:

logo: /assets/images/BM-Logo.png

social:
  name: Brian Mitchell
  links:
    - https://github.com/BrianMitchL
    - https://facebook.com/BrianMitchL
    - https://twitter.com/BrianMitchL
    - https://plus.google.com/+BrianMitchell16/
    - https://www.instagram.com/BrianMitchL
    - http://www.last.fm/user/bman4789
    - https://www.linkedin.com/in/brianscottmitchell
    - https://open.spotify.com/user/1237277662
    - https://soundcloud.com/bman4789
    - https://steamcommunity.com/id/MagicBriBri
    - https://www.youtube.com/user/bman112234
    - https://www.snapchat.com/add/bman4789

google_site_verification: 4-mwXA7aYqZalRm3UuWpPv-aMyFT_zUtA_ks_RK7r5I
